name: probsevere
channels:
  - conda-forge
dependencies:
  # - python=3.9
  - geopy
  - numpy
  - pandas
  - matplotlib
  - basemap
  - scikit-learn 
  - pygrib
  - lxml 
  - pymongo



#*  conda env create --file environment.yml
#*  conda env update --file environment.yml --prune