name: dev-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - basemap
  - scikit-learn 
  - pygrib
  - lxml 
  - pymongo
  - ipykernel
  - jupyterlab


#*  conda env create --file dev-env.yml
#*  conda env update --file dev-env.yml --prune